name: 'check-pr-title'
description: 'Enforce pull request title conventions'

inputs:
  debug:
    description: >
      Enable debug mode.
    required: false
    default: false
  github_token:
    description: >
      Access token used to read the pull requests title.
    required: false
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
