#!/usr/bin/env python3
# hvformat=true

import argparse
import os
import sys


def main():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--help", action="help")
    parser.add_argument(
        "--debug",
        action="store_true",
    )
    parser.add_argument(
        "--github-token",
        nargs=1,
    )
    args = parser.parse_args()

    if args.debug:
        if args.github_token:
            print(f"GITHUB_TOKEN='{args.github_token[0]}'")
        print("--")
        keys = sorted(os.environ.keys())
        for k in keys:
            print(f"{k}={repr(os.environ[k])}")
        print("--")
        event_path = os.environ.get("GITHUB_EVENT_PATH")
        if event_path:
            with open(event_path, 'rt') as f:
                print(f.read())

    if not os.environ.get("CI"):
        print("exiting: $CI not detected.")
        return

    event_name = os.environ.get('GITHUB_EVENT_NAME')
    if event_name != 'pull_request':
        print("exiting: $GITHUB_EVENT_NAME = ", event_name)
        print("$CI not detected. Exiting early.")
        return


if __name__ == "__main__":
    main()
